### ISSUE TITLE
Issue running WMP.py from "/scripts"

### ISSUE THREAD

**Issue by mlazaric97** [mit-crpg/WMP_Library#10]
I am attempting to reproduce the example in the "Usage" portion of the readme. Specifically I cannot load in a library using the method described in the readme i.e. 

u238_multipole = WMP.WindowedMultipole.from_hdf5('092238.h5')

When attempting I get the following error: 
 File "/Users/mlazaric/WMP_Library/scripts/WMP.py", line 428, in from_hdf5
    out.spacing = group['spacing'].value
AttributeError: 'Dataset' object has no attribute 'value'

**Comment by tjlaboss** [comment]
`Dataset.value` was deprecated in h5py 2.1. These scripts need to be updated.

**Comment by jiankai-yu** [comment]
It can be fixed as in the above PR #11.

**Comment by tjlaboss** [comment]
Resolved by PR #11.
