### ISSUE TITLE
Meaning of 'version'

### ISSUE THREAD

**Issue by paulromano** [mit-crpg/WMP_Library#4]
@liangjg Right now, OpenMC checks the version of the multipole library and aborts if it does not match what it expects. Going forward, it seems reasonable to expect a new multipole library (perhaps based on a different data library) that still has the same file format. Should `version` in the HDF5 file be interpreted as "version of the file format" or "version of the data itself"? If the latter, then we shouldn't be aborting OpenMC based on whatever appears.

**Comment by liangjg** [comment]
@paulromano well, I guess it is preferable to interpret the `version` as `version of the file format`, just the same as other io_file formats used in openmc. [This PR ](https://github.com/openmc-dev/openmc/pull/1100) tries to update OpenMC to use the newer library.

**Comment by paulromano** [comment]
Perfect, thanks for the accompanying PR!
