### ISSUE TITLE
Divergence of Faddeeva function

### ISSUE THREAD

**Issue by njchoi** [mit-crpg/WMP_Library#6]
Hello!
I have one more question about the usage of this library.
If my understanding is proper, Im(z) can easily become a large negative value for fluctuating poles because the denominator 2*sqrt(xsi) is a small value due to the Boltzmann constant (= 8.6173303E-05 eV/K).
This causes divergence of my Faddeeva function evalulator.
How did you avoid this problem?
Many thanks in advance!

**Comment by paulromano** [comment]
A different expression is used when Im(z) < 0 as can be seen in [this code](https://github.com/mit-crpg/WMP_Library/blob/master/scripts/WMP.py#L138-L141). This is based on the relation <img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/c267b71baff5ac8983aee4815ba9824688b51c16" />.

**Comment by njchoi** [comment]
Thank you! Seems like a clever idea. I wonder why the Faddeeva functions does not implement it internally.
