### ISSUE TITLE
request for license

### ISSUE THREAD

**Issue by shimwell** [mit-crpg/WMP_Library#7]
Fantastic package, just wondering if there is a usage license for the repository.

As I would like to make use of these h5 data files in the [openmc_data_downloader](https://github.com/openmc-data-storage/openmc_data_downloader) but don't want to break any license terms and conditions.

Thanks for making this

**Comment by liangjg** [comment]
Not sure if anyone else is maintaining this but I'd like to add an MIT License which is commonly used in open repos of CRPG group. Let me know if anyone has any problems.
Thanks.

**Comment by Shimwell** [comment]
That would be idea for my use case :-)

**Comment by tjlaboss** [comment]
MIT license was added in commit d5fe1c4ef3296296b8cded186ca9e7e818e9783c.
