### ISSUE TITLE
OpenW link => not found!

### ISSUE THREAD

**Issue by bassibassi** [mit-crpg/WMP_Library#8]
Hi 
there is a link for OpenW in this page (https://github.com/mit-crpg/WMP_Library)
but it's not working!
is it deleted from Github? how can i access to that code?
thank you!
bassi

**Comment by paulromano** [comment]
Right now that code is on a private repo. @mjlong might be able to speak to whether there are plans to open source it.

**Comment by bassibassi** [comment]
alright, thank you
